# Example project

This is an example project!!

```
this is a verbatim block
   yes, it is!!
```

I'm learning to plot in python!

## some basic examples!

### example plot {#sec:examplePlot1}

Here's an example plot!
<obs time="7/8/25 20:08" author="JF">this is what I observe about the plot there is no space before the debug block</obs>
<err>
    <obs time="7/8/25 20:06" author="JF">I had some problems making the plot</obs>
    then I do some stuff to fix the problems
    <obs time="7/8/25 20:08" author="JF">here are notes about the specific solution</obs>
</err>

<obs time="11/27 16:51">the `alec_BRD` branch doesn't support the 1.5D regularization directly! -- this is why we need the loop</obs>
<obs time="2/15/24 11:55">on coming back to this, note that I have 1.5D working from the $^2$H paper, just note with BRD yet</obs>

<err>
     fix (in file save script): slicing by index yells at me, maybe?

    fix (in file save script): trying to convolve gives me a fine grating, like there's a problem with the enforce causality thing?

    fix (in file save script): two sets of double brackets for assignment doesn't work but comma-separated version works.
</err>

```{python}
from pylab import *
from pyspecdata import *
with figlist_var() as fl:
    fl.next('this is a plot')
    fl.plot(r_[0:10])
```

continue

<err>
    <obs time="7/9/25 11:04" author="JF">maybe I'm having issues continuing!</obs>
    resolve those issues!
    <obs time="7/9/25 11:04" author="JF">I did some stuff, but it was insufficient</obs>
    continue debugging

</err>
