project:
  type: website
  render:
    - 2025-07-08.qmd
    - project1/subproject1/tasks.qmd

execute:
  cache: true
  jupyter: python3

format:
  html:
    extensions: [markdown+raw_html]

filters: [obs.lua]
