#!/usr/bin/env bash
# Generate tags for Python and Quarto files while ignoring the built output

ctags -R \
  --exclude=_site \
  --langdef=quarto --langmap=quarto:.qmd \
  --languages=Python,quarto \
  --regex-quarto='/\{#(sec|fig|tab):([A-Za-z0-9_-]+)\}/\1:\2/s,section/' \
  --regex-quarto='/\[[^\]]+\]\([^#]+#(sec|fig|tab):([A-Za-z0-9_-]+)\)/\1:\2/r,ref/' \
  -f tags
